Numpy 基础

In [2]:
from array import array 

arr = array('i', [i for i in range(1, 8)])

with open('arr.bin', 'wb') as f:
    arr.tofile(f)

arr2 = array('i')
print(arr2)

with open("arr.bin", 'rb') as f:
    arr2.fromfile(f, 7) # 第二个参数控制读入的item数

print(arr2)

array('i')
array('i', [1, 2, 3, 4, 5, 6, 7])


In [3]:
import numpy as np

arr = np.array([3.14, 4, 2, 3])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([3.14, 4.  , 2.  , 3.  ])

In [5]:
import numpy as np

arr = np.array((3, 4), dtype=int)
print(arr)

arr = np.ones_like((3, 4))
print(arr)

arr = np.ones((3, 4), dtype=float)
print(arr)

[3 4]
[1 1]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
a = np.array([1, 2, 3])
print(type(a), type(a[0]), a.shape)
a[0] = 5
print(a)

a = np.array(set(i for i in range(1, 8)))
print(a)

<class 'numpy.ndarray'> <class 'numpy.int64'> (3,)
[5 2 3]
{1, 2, 3, 4, 5, 6, 7}


In [12]:
a = np.ones((2, 3, 4), dtype=np.int16)
print(a)

b = np.zeros((2, 3, 4), dtype=np.int16)
print(b)

c = np.full((2, 2), 7)
print(c)

d = np.eye(3)
print(d)

e = np.random.random((2, 2))
print(e)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.80635165 0.80632512]
 [0.45265903 0.99299843]]


In [15]:
a = np.arange(12).reshape(2, 2, 3)
print(a.strides)

(48, 24, 8)


In [23]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(x + y)
y = x + y
print(y.reshape(1, -1))
print(np.add(x, y))

print(y - x)
y = np.subtract(y, x) - x
print(y)

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))

y = np.sqrt(y)
print(np.sqrt(y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8. 10. 12.]]
[[ 7. 10.]
 [13. 16.]]
[[5. 6.]
 [7. 8.]]
[[4. 4.]
 [4. 4.]]
[[ 4.  8.]
 [12. 16.]]
[[ 4.  8.]
 [12. 16.]]
[[0.25 0.5 ]
 [0.75 1.  ]]
[[0.25 0.5 ]
 [0.75 1.  ]]
[[1.41421356 1.41421356]
 [1.41421356 1.41421356]]


In [31]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4, 8).reshape(2, 2)
z = np.concatenate((y, x), axis=1)
print(z)

z.sort()
print(z)
z.sort(axis=0)
print(z)

[[4 5 0 1]
 [6 7 2 3]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]]


In [33]:
a = np.arange(8).reshape(2, 4)
b = np.full((1, 4), 100)
print(a + b)

c = np.array([3])
print(a * c)

[[100 101 102 103]
 [104 105 106 107]]
[[ 0  3  6  9]
 [12 15 18 21]]


In [36]:
x = np.array([1, 2, 3])
y = np.array([[1, 2, 3]])
print(x.shape, y.shape)

print(x + y)
z = x[:, np.newaxis]
print(z, z.shape)
print(x + z)

(3,) (1, 3)
[[2 4 6]]
[[1]
 [2]
 [3]] (3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]
